const ADD_NEW_TASK = 'ADD_NEW_TASK';
const UPDATE_TASK = 'UPDATE_TASK';
const DELETE_TASK = 'DELETE_TASK';
const EDIT_TASK = 'EDIT_TASK';
const DONE_TASK = 'DONE_TASK';
const CHANGE_THEME = 'CHANGE_THEME';

export {
    ADD_NEW_TASK,
    UPDATE_TASK,
    DELETE_TASK,
    CHANGE_THEME,
    EDIT_TASK,
    DONE_TASK,
}