export const GET_DATA_VIDEO_REQUEST = "APP/HOME_PAGE/GET_DATA_VIDEO_REQUEST";
export const GET_DATA_VIDEO_SUCCESS = "APP/HOME_PAGE/GET_DATA_VIDEO_SUCCESS";
export const GET_DATA_VIDEO_FAILURE = "APP/HOME_PAGE/GET_DATA_VIDEO_FAILURE";

export const UPDATE_DATA_VIDEO_REQUEST =
  "APP/HOME_PAGE/UPDATE_DATA_VIDEO_REQUEST";
export const UPDATE_DATA_VIDEO_SUCCESS =
  "APP/HOME_PAGE/UPDATE_DATA_VIDEO_SUCCESS";
export const UPDATE_DATA_VIDEO_FAILURE =
  "APP/HOME_PAGE/UPDATE_DATA_VIDEO_FAILURE";

export const CREATE_DATA_VIDEO_REQUEST =
  "APP/HOME_PAGE/CREATE_DATA_VIDEO_REQUEST";
export const CREATE_DATA_VIDEO_SUCCESS =
  "APP/HOME_PAGE/CREATE_DATA_VIDEO_SUCCESS";
export const CREATE_DATA_VIDEO_FAILURE =
  "APP/HOME_PAGE/CREATE_DATA_VIDEO_FAILURE";

export const DELETE_DATA_VIDEO_REQUEST =
  "APP/HOME_PAGE/DELETE_DATA_VIDEO_REQUEST";
export const DELETE_DATA_VIDEO_SUCCESS =
  "APP/HOME_PAGE/DELETE_DATA_VIDEO_SUCCESS";
export const DELETE_DATA_VIDEO_FAILURE =
  "APP/HOME_PAGE/DELETE_DATA_VIDEO_FAILURE";

export const CLEAR_DATA_VIDEO = "APP/HOME_PAGE/CLEAR_DATA_VIDEO";
